In [2]:
from matrix_factorisation import nmf_features, transform, transform_2

In [3]:
import cvxpy as cvx
import numpy as np
import pandas as pd

In [4]:
import  os

import numpy as np
import pandas as pd
import pickle
from features import feature_map

In [5]:
import  os

import numpy as np
import pandas as pd


from create_df_larger import read_df_larger
df, dfc, all_homes, appliance_min, national_average = read_df_larger()

df = df.rename(columns={'house_num_rooms':'num_rooms',
                        'num_occupants':'total_occupants',
                        'difference_ratio_min_max':'ratio_difference_min_max'})
K_min, K_max = 1,6
F_min, F_max=1,8

from all_functions import *
from features_larger import *

In [22]:
out = {}
for lat in range(2, 3):
    out[lat]={}
    print lat
    for home in X_normalised.index[:]:
        
        X_home = X_normalised.copy()
        for month in range(start, end):
            X_home.loc[home, '%s_%d' %(appliance, month)] = np.NAN
        mask = X_home.notnull().values
        # Ensure repeatably random problem data.
        A = X_home.copy()
        X, Y, res = nmf_features(A, lat,idx_user, data_user, 10)
        
        pred_df = pd.DataFrame(Y*X)
        pred_df.columns = X_normalised.columns
        pred_df.index = X_normalised.index
        #out[lat][home] = pred_df.ix[home][appliance_cols]
        out[lat][home] = transform_2(pred_df.ix[home], appliance, col_max, col_min)[appliance_cols]

2


In [23]:
pred_df

fridge_1  fridge_2  fridge_3  fridge_4  fridge_5  fridge_6  fridge_7  \
26    0.007846  0.006737  0.007011  0.010193  0.011919  0.011337  0.012304   
59    0.016464  0.015347  0.018327  0.019730  0.021241  0.021331  0.021771   
94    0.004700  0.004381  0.005233  0.005631  0.006061  0.006087  0.006212   
101   0.006954  0.006492  0.007770  0.008320  0.008941  0.008989  0.009162   
222   0.022406  0.019893  0.021972  0.028216  0.032005  0.031051  0.032956   
545   0.010266  0.009051  0.009876  0.013015  0.014863  0.014357  0.015313   
624   0.008446  0.007966  0.009678  0.009995  0.010609  0.010755  0.010860   
661   0.009792  0.008653  0.009481  0.012387  0.014114  0.013653  0.014539   
871   0.009114  0.008523  0.010229  0.010883  0.011671  0.011751  0.011958   
946   0.005030  0.004439  0.004853  0.006372  0.007269  0.007026  0.007489   
1169  0.006689  0.006050  0.006892  0.008270  0.009206  0.009042  0.009465   
1310  0.004458  0.003959  0.004375  0.005612  0.006363  0.006175  0.006552   
1334  0.006014  0.005484  0.006330  0.007375  0.008140  0.008041  0.008362   
1415  0.007799  0.007201  0.008475  0.009440  0.010276  0.010244  0.010543   
1463  0.005574  0.004895  0.005306  0.007092  0.008128  0.007833  0.008377   
1500  0.004495  0.004210  0.005063  0.005360  0.005738  0.005784  0.005878   
1642  0.009813  0.008891  0.010156  0.012113  0.013462  0.013237  0.013837   
1697  0.013207  0.011518  0.012329  0.016917  0.019514  0.018726  0.020123   
1700  0.014949  0.013418  0.015096  0.018625  0.020898  0.020420  0.021499   
1953  0.006573  0.005953  0.006796  0.008116  0.009024  0.008871  0.009276   
2156  0.008320  0.007419  0.008253  0.010434  0.011786  0.011466  0.012132   
2233  0.012395  0.011276  0.012966  0.015237  0.016860  0.016626  0.017323   
2242  0.012649  0.011049  0.011863  0.016176  0.018631  0.017897  0.019210   
2365  0.009230  0.008621  0.010326  0.011038  0.011855  0.011924  0.012148   
2378  0.008818  0.007836  0.008668  0.011094  0.012573  0.012205  0.012946   
2470  0.005734  0.005029  0.005439  0.007305  0.008382  0.008071  0.008639   
2557  0.008053  0.007194  0.008030  0.010079  0.011363  0.011069  0.011695   
2814  0.009442  0.008359  0.009189  0.011922  0.013560  0.013133  0.013966   
2859  0.004338  0.004078  0.004932  0.005151  0.005490  0.005551  0.005621   
2953  0.004970  0.004609  0.005459  0.005990  0.006489  0.006490  0.006655   
...        ...       ...       ...       ...       ...       ...       ...   
4031  0.009785  0.008867  0.010132  0.012076  0.013418  0.013196  0.013792   
4213  0.008521  0.007807  0.009078  0.010398  0.011418  0.011317  0.011724   
4342  0.008406  0.007710  0.008982  0.010246  0.011237  0.011147  0.011537   
4874  0.008595  0.007649  0.008482  0.010798  0.012220  0.011874  0.012581   
4946  0.011394  0.010436  0.012131  0.013908  0.015276  0.015138  0.015685   
4957  0.019644  0.017576  0.019669  0.024551  0.027636  0.026947  0.028439   
4998  0.011125  0.009771  0.010592  0.014155  0.016221  0.015633  0.016718   
5218  0.005022  0.004432  0.004845  0.006360  0.007256  0.007013  0.007475   
5357  0.022917  0.020322  0.022399  0.028893  0.032812  0.031810  0.033791   
5371  0.008281  0.007386  0.008221  0.010383  0.011725  0.011409  0.012069   
6121  0.012120  0.011045  0.012736  0.014871  0.016424  0.016217  0.016873   
6139  0.013150  0.012129  0.014252  0.015936  0.017368  0.017300  0.017821   
6498  0.013081  0.011412  0.012224  0.016750  0.019315  0.018539  0.019917   
6692  0.009601  0.008493  0.009322  0.012134  0.013812  0.013369  0.014227   
6836  0.006171  0.005616  0.006461  0.007583  0.008387  0.008273  0.008618   
6910  0.010523  0.009705  0.011404  0.012753  0.013899  0.013844  0.014262   
7016  0.018052  0.016022  0.017684  0.022741  0.025805  0.025030  0.026573   
7510  0.011931  0.010667  0.011921  0.014922  0.016811  0.016383  0.017300   
7641  0.012764  0.011585  0.013274  0.015725  0.017442  0.017173  0.017926   
7769  0.004295  0.004042  0.

In [19]:
pd.DataFrame(Y).head()

0         1
0  0.504163  0.532436
1  0.999921  0.934086
2  0.285510  0.444400
3  0.428382  0.337422
4  0.715036  0.572690

In [16]:
static_features.head()

area       occ
0  0.531688  0.571429
1  0.935065  1.000000
2  0.444935  0.285714
3  0.337662  0.428571
4  0.571429  0.714286

In [34]:
static_features['occ'].ix[0]=np.NAN

In [49]:
static_features.index.values[static_features.notnull().values]

IndexError: too many indices for array

In [50]:
static_features.notnull().values

array([[ True, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ Tr

In [51]:
np.array([[1,2],[3]])

array([[1, 2], [3]], dtype=object)

In [52]:
X = np.zeros((3,2))

In [53]:
X

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [54]:
X[0,1]=1

In [55]:
X

array([[ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [56]:
X[1,1]=2

In [57]:
X

array([[ 0.,  1.],
       [ 0.,  2.],
       [ 0.,  0.]])

In [72]:
X[:,1][[0]]=np.array([12])

In [76]:
np.where(static_features['occ'].notnull())[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68])

In [75]:
np.where(static_features['area'].notnull())

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68]),)

['None']
