In [1]:
from hmmlearn import hmm

In [2]:

import nilmtk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import OrderedDict
import warnings

In [3]:
warnings.filterwarnings("ignore")


In [4]:
from nilmtk import *
import os
import nilmtk

In [35]:
st = pd.HDFStore(os.path.expanduser("/Users/nipunbatra/wiki-15min.h5"))

In [36]:
metadata_df = pd.read_csv("/Users/nipunbatra/w/dataport-metadata.csv",index_col=0)

In [37]:
feeds = {'use':'aggregate',
        'air1':'hvac',
         'clotheswasher1':'wm',
         'dishwasher1':'dw',
         'microwave1':'mw',
         'refrigerator1':'fridge',
         'oven1':'oven',
        'car1':'ec',
         'waterheater1':'wh',
         'drye1':'dr'
        }

In [38]:
cities = ['Austin','Houston','San Diego','Boulder']

In [39]:
months=12
start='1-1-2015'
start_month=1
end = '12-31-2015'
end_month=12

In [66]:
model = {}
for city in ['San Diego','Austin','Boulder']:
    print city
    print "*"*20
    city_data = metadata_df[metadata_df['city'] == city]
    city_homes = city_data.index.values.astype('int')
    city = city.replace(" ","")
    model[city] = {}
    for appliance in ["air1", "refrigerator1", "clotheswasher1", 
                      "dishwasher1", "microwave1", "car1","oven1","waterheater1","dryer1"]:
        print appliance, "training"
        if appliance in ["refrigerator1"]:
            activation_min = 0.05
        else:
            activation_min = 0.0
        o = []
        for home in city_homes[:50]:
            try:
                dft = st['/%d' %home][appliance][start:end]
                dft = dft.resample("15T", how="mean")
                appl_power = dft.dropna().values.reshape(-1,1)
                activation = (dft>10).sum()*1.0/len(dft)
                
            
                
                if activation>activation_min:
                    o.append(appl_power)
            except:
                pass
        if len(o)>1:
            o = np.array(o)
            mod = hmm.GaussianHMM(3, "full")
            mod.fit(o)
            model[city][feeds[appliance]] = mod
            print "Means for %s are" %appliance
            print mod.means_
        else:
            print "Not enough samples for %s" %appliance
        



San Diego
********************
air1 training
Means for air1 are
[[    0.        ]
 [  349.4476466 ]
 [ 2022.82781261]]
refrigerator1 training
Means for refrigerator1 are
[[  87.05974175]
 [   2.95077789]
 [ 221.86712369]]
clotheswasher1 training
Means for clotheswasher1 are
[[   2.1808973 ]
 [ 104.1043107 ]
 [  24.84099837]]
dishwasher1 training
Means for dishwasher1 are
[[   0.        ]
 [ 563.30253133]
 [  32.83688517]]
microwave1 training
Means for microwave1 are
[[   4.24549058]
 [ 145.44526921]
 [  39.70353194]]
car1 training
Not enough samples for car1
oven1 training
Means for oven1 are
[[    3.56979261]
 [ 2197.96146279]
 [  714.80359473]]
waterheater1 training
Not enough samples for waterheater1
dryer1 training
Not enough samples for dryer1
Austin
********************
air1 training
Means for air1 are
[[  3.00917924e-01]
 [  1.88513596e+03]
 [  4.19637327e+02]]
refrigerator1 training
Means for refrigerator1 are
[[ 110.60030677]
 [ 219.71444707]
 [  32.8040773 ]]
clotheswasher1 t

In [156]:
for city, model_city in model.iteritems():
    new_learnt_models = OrderedDict()
    for appliance, appliance_model in model_city.iteritems():
        startprob, means, covars, transmat = sort_learnt_parameters(
                        appliance_model.startprob_, appliance_model.means_,
                        appliance_model.covars_, appliance_model.transmat_)
        new_learnt_models[appliance] = hmm.GaussianHMM(
                    startprob.size, "full", startprob, transmat)
        new_learnt_models[appliance].means_ = means
        new_learnt_models[appliance].covars_ = covars
        from nilmtk.disaggregate.fhmm_exact import create_combined_hmm
        learnt_model_combined = create_combined_hmm(new_learnt_models)
        from nilmtk.disaggregate.fhmm_exact import FHMM
        f = FHMM()
        f.model = learnt_model_combined
        f.individual = new_learnt_models
        import pickle
        pickle.dump(f, open( "../data/model/fhmm_model_%s.p" %city, "wb" ))

        

In [81]:
out_overall = pickle.load(open('../data/input/all_regions.pkl','r'))


In [89]:
count = 0
for train_region in ["SanDiego","Boulder","Austin"]:
#for train_region in ["SanDiego"]:
    print train_region
    train_df = out_overall[train_region]
    
    for home in train_df.index[:]:
        count+= 1
    
        start = time.time()
        import sys
    
       
        try:
            mains_df = st['/%d' %home][['use']]['2015'].resample("15T")
            pred = f.disaggregate_chunk(mains_df).resample("1M", how="sum").mul(0.000017).mul(15)
            pred.index = pred.index.month
            pred.to_csv("/Users/nipunbatra/wiki-15min-fhmm-out/%s_%d.csv" %(train_region, home))
        except Exception, e:
            pass
        end = time.time()
        print end-start, count, home

SanDiego
0.00564312934875 1 54
62.7728159428 2 203
0.0127511024475 3 527
65.91238904 4 1450
62.0616989136 5 1524
63.7225430012 6 1731
0.0255680084229 7 2031
4.95763111115 8 2354
66.7978720665 9 2606
41.5604820251 10 3687
56.4097380638 11 3864
61.8468880653 12 3938
0.0139148235321 13 4083
0.0149791240692 14 4095
0.0171501636505 15 4329
58.3095200062 16 4495
0.0112240314484 17 4761
58.2195341587 18 4934
0.00973987579346 19 5009
0.0169517993927 20 5909
58.1219499111 21 5938
0.0131340026855 22 6268
4.78457593918 23 6377
0.014575958252 24 6429
0.0159051418304 25 6497
53.0673410892 26 6547
0.002436876297 27 6689
47.5654981136 28 7062
58.226074934 29 7114
0.0159418582916 30 7409
0.0159890651703 31 7639
57.9896481037 32 8061
58.4318621159 33 8342
2.99411797523 34 8574
35.1779170036 35 8733
0.00960111618042 36 8886
26.1193621159 37 9213
0.0172431468964 38 9370
4.03454709053 39 9585
23.9377689362 40 9612
58.4605979919 41 9775
30.4308021069 42 9836
Boulder
57.9967429638 43 232
58.5667600632 44 51

In [146]:
out = {}

for train_region in ["SanDiego","Austin","Boulder"]:
    
    out[train_region] = {}
    train_df = out_overall[train_region]
    for appliance in ["dw",'hvac','fridge','wm','mw','ec','wh','oven']:
        print train_region, appliance
        if appliance=="hvac":
            month_start, month_end = 5, 11
        else:
            month_start, month_end = 1, 13
        out[train_region][appliance] ={}
        for home in train_df.index[1:]:
            try:
                out[train_region][appliance][home] = {}
                pred_df =  pd.read_csv("/Users/nipunbatra/wiki-15min-fhmm-out/%s_%d.csv" %(train_region, home), index_col=0)

                   
                for month in range(month_start, month_end):
                   
                    gt = train_df.ix[home]["%s_%d" %(appliance, month)]
                    pred = pred_df.loc[month,appliance]
                    error = np.abs(gt-pred)
                    error_percentage = 100*error/gt
                    if error_percentage>100:
                        acc=0
                    else:
                        acc = 100-error_percentage
                    out[train_region][appliance][home][month] = acc
            except:
                pass

       

SanDiego dw
SanDiego hvac
SanDiego fridge
SanDiego wm
SanDiego mw
SanDiego ec
SanDiego wh
SanDiego oven
Austin dw
Austin hvac
Austin fridge
Austin wm
Austin mw
Austin ec
Austin wh
Austin oven
Boulder dw
Boulder hvac
Boulder fridge
Boulder wm
Boulder mw
Boulder ec
Boulder wh
Boulder oven


In [141]:
pd.DataFrame(out['SanDiego']['hvac']).mean().mean()

42.2544186457132

In [142]:
pd.DataFrame(out['SanDiego']['dw']).mean().mean()

0.5577280933464502

In [151]:
pd.DataFrame(out['Austin']['oven']).mean().mean()

0.44467711946446686

In [152]:
pd.DataFrame(out['Boulder']['oven']).mean().mean()

1.2656249398860409

In [155]:
pd.DataFrame(out['Austin']['hvac']).mean().mean()

60.423992969632025

In [158]:
sd_sd_nilm = {}
for appliance in ["dw",'hvac','fridge','wm','mw','ec','wh','oven']:
    sd_sd_nilm[appliance] = pd.DataFrame(out['SanDiego'][appliance]).mean().mean()

In [159]:
sd_sd_nilm

{'dw': 0.5577280933464502,
 'ec': nan,
 'fridge': 50.985555403149746,
 'hvac': 42.2544186457132,
 'mw': 3.681773127817756,
 'oven': 7.0739244574788955,
 'wh': nan,
 'wm': 1.1108455368999053}

In [161]:
pd.DataFrame(out['SanDiego']['hvac'])

203   527        1450       1524       1731  2031  2354       2606  \
5    0.000000   NaN   0.000000   0.000000   0.000000   NaN   NaN   0.000000   
6   92.137173   NaN  84.614866  84.682535  46.393935   NaN   NaN  76.633997   
7   70.763907   NaN  93.087525  83.351962  88.188977   NaN   NaN  92.201126   
8   61.540052   NaN  84.234883  72.917393  76.960231   NaN   NaN  77.641166   
9   72.414384   NaN  80.858820  71.973663  76.534135   NaN   NaN  83.082583   
10  96.714561   NaN  92.523013  95.358362  95.840624   NaN   NaN  92.537795   

         3687       3864  ...        8342  8574       8733  8886  9213  9370  \
5    0.000000   0.000000  ...    0.000000   NaN   0.000000   NaN     0   NaN   
6   54.549238   0.000000  ...    0.000000   NaN   0.000000   NaN     0   NaN   
7   96.582655  80.035744  ...    0.000000   NaN  90.715851   NaN   NaN   NaN   
8   82.524598  64.563849  ...   85.586980   NaN  71.759366   NaN   NaN   NaN   
9   57.828430  57.569448  ...   36.116643   NaN        NaN   NaN   NaN   NaN   
10        NaN  71.594192  ...    0.000000   NaN        NaN   NaN   NaN   NaN   

    9585       9612       9775  9836  
5    NaN  20.394375   0.000000     0  
6    NaN   0.000000   0.000000     0  
7    NaN        NaN   0.000000     0  
8    NaN        NaN  87.398325   NaN  
9    NaN        NaN  68.811208   NaN  
10   NaN        NaN  82.287267   NaN  

[6 rows x 41 columns]

In [162]:
austin_austin_nilm = {}
for appliance in ["dw",'hvac','fridge','wm','mw','ec','wh','oven']:
    austin_austin_nilm[appliance] = pd.DataFrame(out['Austin'][appliance]).mean().mean()

In [163]:
austin_austin_nilm

{'dw': 0.2785754646785667,
 'ec': nan,
 'fridge': 53.15558262517974,
 'hvac': 60.423992969632025,
 'mw': 3.3594100938387794,
 'oven': 0.44467711946446686,
 'wh': nan,
 'wm': 1.3666039865794135}